default:
  primary: kite
  fallback: []

exchanges:
  NSE:
    primary: kite
    fallback: []
  BSE:
    primary: kite
    fallback: []
  NASDAQ:
    primary: alpaca
    fallback: []
  NYSE:
    primary: alpaca
    fallback: []
  CRYPTO:
    primary: crypto
    fallback: []
