"""EURUSD point-in-time Historical Intelligence backtest (continuation directive).

Reuses the EXISTING, unmodified production pipeline end to end -- no new fingerprint/statistics/
verdict logic is written here:

  - Candidates come from real HistoricalPatternFingerprintORM rows already generated by
    bulk_replay.py (the SAME production strategy/fingerprint code a live candidate uses).
  - The historical verdict for each one is computed via similarity.similarity_statistics(...,
    as_of=entry_time - purge) -- the EXACT same walk-forward-safe mechanism similarity_oos.py's
    calibration_check already uses, restricted to STRICTLY EARLIER analogs only.
  - The verdict itself (SUPPORT/RANK_ADJUST/DEFER/REJECT/NEUTRAL/INSUFFICIENT) is produced by
    entry_intelligence.py's own _normalize_similarity_stats + _evaluate_from_stats -- the exact
    scoring/threshold logic the live DEMO decision path uses (_historical_score,
    _SUPPORT_SCORE_THRESHOLD=15, _DEFER_SCORE_THRESHOLD=-15, _MIN_SAMPLE_FOR_LIVE_INFLUENCE=100).
  - "Revealing the future" is reading the ALREADY-COMPUTED HistoricalSetupOutcomeORM row for that
    same fingerprint -- outcomes.py already resolved it using ONLY candles strictly after
    entry_time (no new lookahead-prone code).

This script's only real contribution is orchestration + aggregate scoring (calibration, ESS
threshold sensitivity, SUPPORT/OPPOSE hit rates) over MANY real candidates instead of one.
"""
from __future__ import annotations

import json
import os
from datetime import timedelta

from backend.historical_intelligence import entry_intelligence, similarity
from backend.historical_intelligence.orm import HistoricalPatternFingerprintORM, HistoricalSetupOutcomeORM
from backend.historical_intelligence.walk_forward import _PURGE_WINDOW
from backend.shared.db import SessionLocal

SYMBOL = "EURUSD"
ESS_THRESHOLDS = [20, 30, 50, 75, 100, 150]
# Each candidate costs 2 real similarity_statistics DB queries -- evaluating the FULL corpus
# (60,000+ EURUSD candidates once MT5's own ongoing corpus is included) is real, valuable work
# but takes hours. SAMPLE_STRIDE takes every Nth chronological candidate instead, preserving
# coverage across the full date range/regime mix (never a random subset that could cluster) while
# keeping a single run practical. Set to 1 for the full, exhaustive corpus.
SAMPLE_STRIDE = 15


def _dims(fp):
    return similarity._fingerprint_to_dims(fp)


def load_candidates(symbol: str) -> list[tuple]:
    with SessionLocal() as db:
        rows = (
            db.query(HistoricalPatternFingerprintORM, HistoricalSetupOutcomeORM)
            .join(HistoricalSetupOutcomeORM, HistoricalSetupOutcomeORM.fingerprint_id == HistoricalPatternFingerprintORM.fingerprint_id)
            .filter(
                HistoricalPatternFingerprintORM.canonical_symbol == symbol,
                HistoricalSetupOutcomeORM.resolution_status == "RESOLVED",
                HistoricalSetupOutcomeORM.data_quality != "UNTRUSTED",
            )
            .order_by(HistoricalPatternFingerprintORM.entry_time.asc())
            .all()
        )
    return rows


def evaluate_one(fp, outcome) -> dict:
    as_of = fp.entry_time - _PURGE_WINDOW
    sim_stats = similarity.similarity_statistics(
        canonical_symbol=fp.canonical_symbol, direction=fp.direction, anchor_strategy=fp.anchor_strategy,
        strategy_version=fp.strategy_version, query_dims=_dims(fp), regime_broad=fp.regime_broad,
        top_k=100, as_of=as_of,
    )
    normalized = entry_intelligence._normalize_similarity_stats(sim_stats)
    verdict_result = entry_intelligence._evaluate_from_stats(
        trust_state="BACKTEST", stats=normalized, peer_group_hash=fp.peer_group_hash,
        source="SIMILARITY_WEIGHTED_BACKTEST", evaluation_source="SIMILARITY_WEIGHTED",
    )

    # Part 9: SAME candidate, SAME as_of, restricted to an MT5-only neighbor pool -- isolates
    # whether ForexSB's added depth actually changes the evidence, not just whether it exists.
    mt5_only_stats = similarity.similarity_statistics(
        canonical_symbol=fp.canonical_symbol, direction=fp.direction, anchor_strategy=fp.anchor_strategy,
        strategy_version=fp.strategy_version, query_dims=_dims(fp), regime_broad=fp.regime_broad,
        top_k=100, as_of=as_of, providers={"MT5"},
    )
    return {
        "fingerprint_id": fp.fingerprint_id,
        "entry_time": fp.entry_time.isoformat(),
        "provider": fp.provider,
        "strategy": fp.anchor_strategy,
        "direction": fp.direction,
        "regime": fp.regime,
        "session": fp.session,
        "raw_neighbor_count": sim_stats.get("raw_neighbor_count", 0),
        "very_close_matches": sim_stats.get("very_close_matches", 0),
        "effective_sample_size": sim_stats.get("effective_sample_size", 0.0),
        "median_similarity": sim_stats.get("median_similarity"),
        "min_similarity": sim_stats.get("similarity_weight_distribution", {}).get("min") if sim_stats.get("similarity_weight_distribution") else None,
        "predicted_p_1r": sim_stats.get("weighted_probability_1r"),
        "predicted_p_2r": sim_stats.get("weighted_probability_2r"),
        "predicted_p_tp": sim_stats.get("weighted_probability_tp"),
        "predicted_p_sl": sim_stats.get("weighted_probability_sl"),
        "predicted_expectancy_r": sim_stats.get("weighted_expectancy_r"),
        "historical_score": verdict_result.get("historical_score"),
        "historical_decision": verdict_result.get("historical_decision"),
        "status": verdict_result.get("status"),
        # MT5-only comparison (Part 9)
        "mt5_only_raw_neighbor_count": mt5_only_stats.get("raw_neighbor_count", 0),
        "mt5_only_effective_sample_size": mt5_only_stats.get("effective_sample_size", 0.0),
        "mt5_only_predicted_expectancy_r": mt5_only_stats.get("weighted_expectancy_r"),
        "mt5_only_predicted_p_1r": mt5_only_stats.get("weighted_probability_1r"),
        "mt5_only_status": mt5_only_stats.get("status"),
        # revealed future (already computed, forward-only, by outcomes.py)
        "actual_outcome_r": outcome.outcome_r,
        "actual_reached_1r": outcome.reached_1r,
        "actual_reached_2r": outcome.reached_2r,
        "actual_tp_hit": outcome.tp_hit,
        "actual_sl_hit": outcome.sl_hit,
        "actual_mfe_r": outcome.mfe_r,
        "actual_mae_r": outcome.mae_r,
        "actual_immediate_failure": outcome.immediate_failure,
    }


def ess_threshold_analysis(records: list[dict]) -> dict:
    """Part 5: for each candidate ESS threshold, only count a candidate as 'qualifying' if its
    effective_sample_size clears that bar, then measure real calibration/expectancy AT that
    threshold -- determines empirically where prediction becomes reliable, rather than assuming."""
    report = {}
    for thresh in ESS_THRESHOLDS:
        qualifying = [r for r in records if r["effective_sample_size"] >= thresh and r["actual_outcome_r"] is not None]
        if not qualifying:
            report[thresh] = {"n": 0}
            continue
        n = len(qualifying)
        mean_predicted_p1r = sum(r["predicted_p_1r"] for r in qualifying if r["predicted_p_1r"] is not None) / max(1, sum(1 for r in qualifying if r["predicted_p_1r"] is not None))
        actual_reach_1r_rate = sum(1 for r in qualifying if r["actual_reached_1r"]) / n
        mean_predicted_r = sum(r["predicted_expectancy_r"] for r in qualifying if r["predicted_expectancy_r"] is not None) / max(1, sum(1 for r in qualifying if r["predicted_expectancy_r"] is not None))
        mean_actual_r = sum(r["actual_outcome_r"] for r in qualifying) / n
        # Brier score component for P(1R): predicted probability vs binary actual outcome.
        brier_terms = [(r["predicted_p_1r"] - (1.0 if r["actual_reached_1r"] else 0.0)) ** 2 for r in qualifying if r["predicted_p_1r"] is not None]
        brier = sum(brier_terms) / len(brier_terms) if brier_terms else None
        calibration_mae = abs(mean_predicted_p1r - actual_reach_1r_rate) if mean_predicted_p1r is not None else None
        report[thresh] = {
            "n": n,
            "mean_predicted_p_1r": round(mean_predicted_p1r, 4) if mean_predicted_p1r is not None else None,
            "actual_reach_1r_rate": round(actual_reach_1r_rate, 4),
            "calibration_mae_p1r": round(calibration_mae, 4) if calibration_mae is not None else None,
            "brier_score_p1r": round(brier, 4) if brier is not None else None,
            "mean_predicted_expectancy_r": round(mean_predicted_r, 4),
            "mean_actual_expectancy_r": round(mean_actual_r, 4),
        }
    return report


def mt5_only_vs_combined(records: list[dict]) -> dict:
    """Part 9: for the SAME candidates, compare MT5-only evidence against MT5+ForexSB combined
    evidence -- coverage, ESS, and (where both produced a resolvable prediction) expectancy
    accuracy against the real revealed outcome. Never assumes more data is automatically better;
    reports the real delta."""
    resolved = [r for r in records if r["actual_outcome_r"] is not None]
    n = len(resolved)
    if n == 0:
        return {"n": 0}
    combined_unavailable = sum(1 for r in resolved if r["status"] == "UNAVAILABLE")
    mt5_only_unavailable = sum(1 for r in resolved if r["mt5_only_status"] == "UNAVAILABLE")
    combined_mean_ess = sum(r["effective_sample_size"] for r in resolved) / n
    mt5_only_mean_ess = sum(r["mt5_only_effective_sample_size"] for r in resolved) / n

    both_predicted = [r for r in resolved if r["predicted_expectancy_r"] is not None and r["mt5_only_predicted_expectancy_r"] is not None]
    combined_mae = mt5_only_mae = None
    if both_predicted:
        combined_mae = sum(abs(r["predicted_expectancy_r"] - r["actual_outcome_r"]) for r in both_predicted) / len(both_predicted)
        mt5_only_mae = sum(abs(r["mt5_only_predicted_expectancy_r"] - r["actual_outcome_r"]) for r in both_predicted) / len(both_predicted)

    return {
        "n": n,
        "combined_unavailable_rate": round(combined_unavailable / n, 4),
        "mt5_only_unavailable_rate": round(mt5_only_unavailable / n, 4),
        "combined_mean_ess": round(combined_mean_ess, 2),
        "mt5_only_mean_ess": round(mt5_only_mean_ess, 2),
        "both_had_prediction_n": len(both_predicted),
        "combined_expectancy_mean_abs_error": round(combined_mae, 4) if combined_mae is not None else None,
        "mt5_only_expectancy_mean_abs_error": round(mt5_only_mae, 4) if mt5_only_mae is not None else None,
        "combined_more_accurate": (combined_mae < mt5_only_mae) if (combined_mae is not None and mt5_only_mae is not None) else None,
    }


def verdict_breakdown(records: list[dict]) -> dict:
    by_verdict: dict[str, list[dict]] = {}
    for r in records:
        by_verdict.setdefault(r["historical_decision"], []).append(r)
    out = {}
    for verdict, items in by_verdict.items():
        resolved = [i for i in items if i["actual_outcome_r"] is not None]
        n = len(resolved)
        mean_actual_r = sum(i["actual_outcome_r"] for i in resolved) / n if n else None
        mean_predicted_r = sum(i["predicted_expectancy_r"] for i in resolved if i["predicted_expectancy_r"] is not None) / max(1, sum(1 for i in resolved if i["predicted_expectancy_r"] is not None)) if resolved else None
        out[verdict] = {"count": len(items), "resolved_n": n, "mean_actual_outcome_r": round(mean_actual_r, 4) if mean_actual_r is not None else None, "mean_predicted_expectancy_r": round(mean_predicted_r, 4) if mean_predicted_r is not None else None}
    return out


def main() -> None:
    all_rows = load_candidates(SYMBOL)
    rows = all_rows[::SAMPLE_STRIDE] if SAMPLE_STRIDE > 1 else all_rows
    print(f"Loaded {len(all_rows)} resolved {SYMBOL} candidates (any provider); sampling every {SAMPLE_STRIDE} chronologically -> {len(rows)} to evaluate", flush=True)
    if not rows:
        print("NO CANDIDATES AVAILABLE YET -- corpus not ready for this symbol.", flush=True)
        return

    # Resume support: candidate order is deterministic (same query, same stride), so on restart
    # after a crash we reload any already-checkpointed records and skip re-evaluating them --
    # this is a resume of already-computed results, not a change to what gets computed.
    records: list[dict] = []
    start_index = 0
    if os.path.exists("/app/eurusd_backtest_records.json"):
        try:
            with open("/app/eurusd_backtest_records.json") as f:
                prior = json.load(f)
            if isinstance(prior, list) and prior and all(
                r.get("fingerprint_id") == rows[idx][0].fingerprint_id for idx, r in enumerate(prior)
            ):
                records = prior
                start_index = len(prior)
                print(f"Resuming from checkpoint: {start_index}/{len(rows)} already evaluated.", flush=True)
        except (json.JSONDecodeError, OSError, IndexError):
            print("Checkpoint file present but unusable -- starting fresh.", flush=True)

    for i, (fp, outcome) in enumerate(rows):
        if i < start_index:
            continue
        try:
            records.append(evaluate_one(fp, outcome))
        except Exception as exc:
            print(f"  [{i}] evaluation failed for {fp.fingerprint_id}: {exc.__class__.__name__}: {exc}", flush=True)
        if (i + 1) % 200 == 0:
            print(f"  ...evaluated {i + 1}/{len(rows)}", flush=True)
        # Durable checkpoint every 500 candidates so a process death (Docker restart, host
        # reboot, etc.) never loses more than 500 candidates of already-completed evaluation.
        # Written atomically (temp file + rename) so a crash mid-write can't corrupt the file.
        if (i + 1) % 500 == 0 or (i + 1) == len(rows):
            tmp_path = "/app/eurusd_backtest_records.json.tmp"
            with open(tmp_path, "w") as f:
                json.dump(records, f, indent=2, default=str)
            os.replace(tmp_path, "/app/eurusd_backtest_records.json")
            with open("/app/eurusd_backtest_progress.json", "w") as f:
                json.dump({"evaluated": i + 1, "total": len(rows)}, f)
            print(f"  [checkpoint] {i + 1}/{len(rows)} written to /app/eurusd_backtest_records.json", flush=True)

    print(f"\nEvaluated {len(records)} candidates.", flush=True)
    print("\n=== ESS THRESHOLD ANALYSIS ===", flush=True)
    print(json.dumps(ess_threshold_analysis(records), indent=2, default=str), flush=True)

    print("\n=== VERDICT BREAKDOWN ===", flush=True)
    print(json.dumps(verdict_breakdown(records), indent=2, default=str), flush=True)

    print("\n=== MT5-ONLY vs MT5+FOREXSB (Part 9) ===", flush=True)
    print(json.dumps(mt5_only_vs_combined(records), indent=2, default=str), flush=True)

    raw100 = sum(1 for r in records if r["raw_neighbor_count"] >= 100)
    print(f"\nCandidates with raw_neighbor_count >= 100: {raw100}/{len(records)}", flush=True)
    ess_dist = sorted(r["effective_sample_size"] for r in records)
    if ess_dist:
        print(f"Effective sample size distribution: min={ess_dist[0]:.1f} median={ess_dist[len(ess_dist)//2]:.1f} max={ess_dist[-1]:.1f}", flush=True)

    with open("/app/eurusd_backtest_records.json", "w") as f:
        json.dump(records, f, indent=2, default=str)
    print("\nFull per-candidate records written to /app/eurusd_backtest_records.json", flush=True)


if __name__ == "__main__":
    main()
