"""Phase 1 flag A/B validation harness (2026-08-20): point-in-time comparison of
breakout/trend_pullback/smc_continuation with the architecture-blueprint Section 4 "Phase 1"
flags OFF (baseline -- matches current production defaults, already the corpus behind the earlier
8-year audit) vs ON, across the full available M15 history (~2018-08 to ~2026-08, minus the last
~8.3 days needed for outcome resolution) for all 10 traded symbols.

SAFETY: strictly READ-ONLY against the database (only ever SELECTs mt5_canonical_candles /
mt5_candle_revisions). NEVER writes to historical_pattern_fingerprints / historical_setup_outcomes
-- this is a one-off research comparison, not a corpus-expansion run, and must never contaminate
the live corpus backend.historical_intelligence.entry_intelligence.py reads for real (DEMO)
trading decisions happening right now. Baseline ("before") is NOT recomputed here -- it already
exists in the DB (generated by bulk_replay.py under flags-off, i.e. current production code) and
is read directly via SQL by the companion aggregation step.

Bars are bulk-preloaded ONCE per symbol/timeframe (10 symbols x 3 timeframes = 30 queries total)
rather than making ~2M individual bars_as_of() DB round trips -- bulk_replay.py's own docstring
documents that per-instant DB-query path at ~7s/instant, which would make a full 8-year x
10-symbol run take weeks. After preload, the walk-forward context build + evaluation + outcome
computation all run entirely in memory. Reuses real production code UNMODIFIED for everything
that determines whether/how a strategy fires: build_strategy_context, evaluate_breakout,
evaluate_trend_pullback, evaluate_smc_continuation (imported directly from
backend.mt5_strategies.*, same functions live trading and bulk_replay.py call). Only the bar-
loading/windowing and outcome-resolution plumbing are new code, written for this comparison.

Outcome computation reproduces outcomes.py::label_outcome's exact R-multiple/immediate-failure
algorithm bar-for-bar (same milestone thresholds, same SL-touched-first tie-break, same
_IMMEDIATE_FAILURE_ADVERSE_FRACTION/_MAX_LOOKFORWARD_BARS constants, imported not re-typed) but
walks the SAME in-memory M15 array already loaded for context-building instead of that module's
own DB-querying _future_candles_with_quality. Documented simplification: skips the HIGH/
ACCEPTABLE/APPROXIMATE/UNTRUSTED revision-quality tiering (irrelevant here -- every bar in this
2018-2025 window is long since settled/finalized regardless of which revision resolved it), and
prefers the latest MT5CandleRevisionORM row when one exists, else the canonical row, computed once
in bulk rather than per-instant -- correct for a comparative research pass, not a substitute for
outcomes.py's own production labeling path.

Usage (inside the backend container):
  python scratch_phase1_flag_ab_replay.py --symbols EURUSD XAUUSD --max-instants 5000 --out /tmp/pilot.json
  python scratch_phase1_flag_ab_replay.py --out /tmp/full_run.json          # full 10-symbol, full-history run
"""
from __future__ import annotations

import argparse
import json
import os
import time
from dataclasses import asdict, dataclass
from datetime import datetime, timedelta, timezone
from decimal import Decimal
from typing import Any

# Phase 1 flags ON, set BEFORE importing/calling the evaluators (they read env vars at call time
# via os.environ.get, so this must happen before evaluate_breakout/trend_pullback/smc_continuation
# are ever invoked below -- setting them at module import time here guarantees that).
os.environ["MT5_BREAKOUT_ATR_BUFFER_ENABLED"] = "true"
os.environ["MT5_BREAKOUT_ATR_BUFFER_MULT"] = "0.5"
os.environ["MT5_BREAKOUT_ENTRY_MODE"] = "RETEST_AND_HOLD"
os.environ["MT5_BREAKOUT_HTF_GATE_ENABLED"] = "true"
os.environ["MT5_TREND_PULLBACK_ANTI_CHOCH_GATE_ENABLED"] = "true"
os.environ["MT5_TREND_PULLBACK_CONFLUENCE_MODE"] = "OTE_OB_FVG"
os.environ["MT5_TREND_PULLBACK_REACTION_CANDLE_REQUIRED"] = "true"
os.environ["MT5_SMC_CONTINUATION_IDM_REQUIRED"] = "true"

from sqlalchemy import text  # noqa: E402

from backend.brokers.mt5.models import MT5Candle  # noqa: E402
from backend.historical_intelligence.outcomes import _IMMEDIATE_FAILURE_ADVERSE_FRACTION, _MAX_LOOKFORWARD_BARS, _R_MILESTONES  # noqa: E402
from backend.historical_intelligence.replay import _row_to_candle  # noqa: E402
from backend.market_structure.engine import analyze_bars  # noqa: E402
from backend.mt5_strategies.context import build_strategy_context  # noqa: E402
from backend.mt5_strategies.families.breakout import evaluate_breakout  # noqa: E402
from backend.mt5_strategies.families.smc_continuation import evaluate_smc_continuation  # noqa: E402
from backend.mt5_strategies.families.trend_pullback import evaluate_trend_pullback  # noqa: E402
from backend.shared.db import SessionLocal  # noqa: E402

_STRATEGIES = {
    "breakout": evaluate_breakout,
    "trend_pullback": evaluate_trend_pullback,
    "smc_continuation": evaluate_smc_continuation,
}
_TF_DELTA = {"M15": timedelta(minutes=15), "H1": timedelta(hours=1), "H4": timedelta(hours=4)}
_ALL_SYMBOLS = ("EURUSD", "GBPUSD", "USDJPY", "AUDUSD", "NZDUSD", "USDCAD", "USDCHF", "EURJPY", "GBPJPY", "XAUUSD")
_LOOKBACK_BARS = 100
_MIN_BARS = 60  # smallest of the 3 strategies' own history floors (trend_pullback checks len(closes) < 60)


def _ensure_utc(dt: datetime) -> datetime:
    return dt if dt.tzinfo else dt.replace(tzinfo=timezone.utc)


def _load_symbol_timeframe(symbol: str, timeframe: str) -> list[MT5Candle]:
    """One bulk read per symbol/timeframe: latest MT5CandleRevisionORM row per bar (when any
    exist) else the MT5CanonicalCandleORM row, ascending by time. Mirrors replay.py::bars_as_of's
    tier-2/tier-3 source hierarchy, computed once in bulk instead of per look-back window.

    Deliberately NOT filtered by provider: the real baseline corpus for these 3 strategies is
    itself a two-provider stitch (confirmed via historical_pattern_fingerprints: FOREXSB covers
    ~2018-08 to ~2024-08, MT5 picks up ~2024-08 onward once this deployment's live demo accounts
    started accumulating real broker-fed history) -- hardcoding provider='MT5' here would silently
    truncate most symbols to only their most recent ~2 years and make the flags-ON comparison
    non-comparable to the flags-OFF baseline it's being measured against."""
    with SessionLocal() as db:
        revision_rows = db.execute(
            text(
                """
                SELECT DISTINCT ON (bar_timestamp_utc) bar_timestamp_utc, open, high, low, close, tick_volume, spread, real_volume, provider
                FROM mt5_candle_revisions
                WHERE broker_symbol = :symbol AND timeframe = :tf
                ORDER BY bar_timestamp_utc, revision_number DESC
                """
            ),
            {"symbol": symbol, "tf": timeframe},
        ).fetchall()
        canonical_rows = db.execute(
            text(
                """
                SELECT COALESCE(timestamp_utc, timestamp) AS bar_time, open, high, low, close, tick_volume, spread, real_volume, provider
                FROM mt5_canonical_candles
                WHERE broker_symbol = :symbol AND timeframe = :tf AND quality != 'INVALID'
                ORDER BY bar_time
                """
            ),
            {"symbol": symbol, "tf": timeframe},
        ).fetchall()

    resolved: dict[datetime, Any] = {}
    for row in canonical_rows:
        resolved[_ensure_utc(row.bar_time)] = row
    for row in revision_rows:
        resolved[_ensure_utc(row.bar_timestamp_utc)] = row  # revisions win when both exist

    candles = []
    for bar_time in sorted(resolved.keys()):
        row = resolved[bar_time]
        candles.append(_row_to_candle(symbol, timeframe, bar_time, row))
    return candles


@dataclass
class _Trade:
    strategy_id: str
    symbol: str
    direction: str
    entry_time: str
    entry: float
    stop_loss: float
    take_profit: float
    outcome_r: float | None
    tp_hit: bool | None
    sl_hit: bool | None
    immediate_failure: bool | None
    resolution_status: str
    mfe_r: float | None
    mae_r: float | None
    holding_bars: int | None


def _compute_outcome(*, direction: str, entry: float, stop_loss: float, take_profit: float, future_m15: list[MT5Candle]) -> dict[str, Any]:
    """Bar-for-bar reproduction of outcomes.py::label_outcome's algorithm, reading forward bars
    from an in-memory slice instead of a DB query. See module docstring for the documented
    quality-tiering simplification."""
    risk = abs(entry - stop_loss)
    if risk <= 0:
        return {"resolution_status": "INSUFFICIENT_FUTURE_DATA"}
    long = direction.upper() == "LONG"
    candles = future_m15[:_MAX_LOOKFORWARD_BARS]
    if not candles:
        return {"resolution_status": "PENDING"}

    max_favorable = 0.0
    max_adverse = 0.0
    milestone_times: dict[float, int] = {}
    reached_before_adverse_failure = False
    resolution: dict[str, Any] | None = None

    for idx, candle in enumerate(candles):
        high, low, close = float(candle.high), float(candle.low), float(candle.close)
        favorable = (high - entry) if long else (entry - low)
        adverse = (entry - low) if long else (high - entry)
        if favorable > max_favorable:
            max_favorable = favorable
        max_adverse = max(max_adverse, adverse)

        favorable_r_now = max_favorable / risk
        for milestone in _R_MILESTONES:
            if milestone not in milestone_times and favorable_r_now >= milestone:
                milestone_times[milestone] = idx
        if not reached_before_adverse_failure and favorable_r_now >= 0.25:
            reached_before_adverse_failure = True

        sl_touched = (low <= stop_loss) if long else (high >= stop_loss)
        tp_touched = (high >= take_profit) if long else (low <= take_profit)
        if sl_touched or tp_touched:
            if sl_touched:
                resolution = {"tp_hit": False, "sl_hit": True, "outcome_r": -1.0, "resolved_idx": idx}
            else:
                planned_rr = abs(take_profit - entry) / risk
                resolution = {"tp_hit": True, "sl_hit": False, "outcome_r": planned_rr, "resolved_idx": idx}
            break

    immediate_failure = (max_adverse / risk >= _IMMEDIATE_FAILURE_ADVERSE_FRACTION) and not reached_before_adverse_failure
    base = {
        "mfe_r": round(max_favorable / risk, 4), "mae_r": round(max_adverse / risk, 4),
        "immediate_failure": immediate_failure,
    }
    if resolution is not None:
        base.update({
            "resolution_status": "RESOLVED", "outcome_r": round(resolution["outcome_r"], 4),
            "tp_hit": resolution["tp_hit"], "sl_hit": resolution["sl_hit"], "holding_bars": resolution["resolved_idx"] + 1,
        })
    elif len(candles) >= _MAX_LOOKFORWARD_BARS:
        last_close = float(candles[-1].close)
        mtm_r = ((last_close - entry) / risk) * (1.0 if long else -1.0)
        base.update({"resolution_status": "RESOLVED", "outcome_r": round(mtm_r, 4), "tp_hit": False, "sl_hit": False, "holding_bars": len(candles)})
    else:
        base["resolution_status"] = "PENDING"
    return base


def replay_symbol(symbol: str, *, max_instants: int | None, progress_every: int, lookback_years: float | None = None) -> list[_Trade]:
    t0 = time.perf_counter()
    m15 = _load_symbol_timeframe(symbol, "M15")
    h1 = _load_symbol_timeframe(symbol, "H1")
    h4 = _load_symbol_timeframe(symbol, "H4")
    print(f"[{symbol}] loaded m15={len(m15)} h1={len(h1)} h4={len(h4)} in {time.perf_counter()-t0:.1f}s", flush=True)
    if len(m15) < _LOOKBACK_BARS + _MAX_LOOKFORWARD_BARS:
        print(f"[{symbol}] insufficient M15 history, skipping", flush=True)
        return []

    trades: list[_Trade] = []
    h1_ptr, h4_ptr = -1, -1
    h1_snapshot_cache: tuple[int, Any] | None = None
    h4_snapshot_cache: tuple[int, Any] | None = None

    start_idx = _LOOKBACK_BARS - 1
    end_idx = len(m15) - _MAX_LOOKFORWARD_BARS - 1  # leave room for full outcome lookforward
    window_label = "full history"
    if lookback_years is not None:
        cutoff = m15[end_idx].time - timedelta(days=lookback_years * 365.25)
        cutoff_idx = start_idx
        for j in range(start_idx, end_idx):
            if m15[j].time >= cutoff:
                cutoff_idx = j
                break
        else:
            cutoff_idx = end_idx
        start_idx = max(start_idx, cutoff_idx)
        window_label = f"most recent {lookback_years:g}y (from {m15[start_idx].time.isoformat()})"
    print(f"[{symbol}] walk window: {window_label}, {end_idx - start_idx} instants available", flush=True)
    instants_done = 0
    t_loop = time.perf_counter()

    for i in range(start_idx, end_idx):
        if max_instants is not None and instants_done >= max_instants:
            break
        instants_done += 1
        at = m15[i].time + _TF_DELTA["M15"]
        m15_window = m15[i - _LOOKBACK_BARS + 1 : i + 1]

        while h1_ptr + 1 < len(h1) and h1[h1_ptr + 1].time + _TF_DELTA["H1"] <= at:
            h1_ptr += 1
        while h4_ptr + 1 < len(h4) and h4[h4_ptr + 1].time + _TF_DELTA["H4"] <= at:
            h4_ptr += 1
        if h1_ptr < _MIN_BARS - 1 or h4_ptr < 30 - 1:
            continue
        h1_window = h1[max(0, h1_ptr - _LOOKBACK_BARS + 1) : h1_ptr + 1]
        h4_window = h4[max(0, h4_ptr - _LOOKBACK_BARS + 1) : h4_ptr + 1]

        if h1_snapshot_cache is not None and h1_snapshot_cache[0] == h1_ptr:
            h1_snapshot = h1_snapshot_cache[1]
        else:
            h1_rows_tmp = [c.model_dump(mode="json") for c in h1_window]
            h1_snapshot = analyze_bars(h1_rows_tmp, symbol=symbol, timeframe="H1")
            h1_snapshot_cache = (h1_ptr, h1_snapshot)
        if h4_snapshot_cache is not None and h4_snapshot_cache[0] == h4_ptr:
            h4_snapshot = h4_snapshot_cache[1]
        else:
            h4_rows_tmp = [c.model_dump(mode="json") for c in h4_window]
            h4_snapshot = analyze_bars(h4_rows_tmp, symbol=symbol, timeframe="H4")
            h4_snapshot_cache = (h4_ptr, h4_snapshot)

        m15_rows = [c.model_dump(mode="json") for c in m15_window]
        h1_rows = [c.model_dump(mode="json") for c in h1_window]
        h4_rows = [c.model_dump(mode="json") for c in h4_window]
        last_close = m15_window[-1].close

        try:
            ctx = build_strategy_context(
                symbol=symbol, broker_symbol=symbol, m15_rows=m15_rows, h1_rows=h1_rows, h4_rows=h4_rows,
                bid=last_close, ask=last_close, spread=Decimal("0"), now=at,
                h1_snapshot=h1_snapshot, h4_snapshot=h4_snapshot,
            )
        except Exception as exc:
            print(f"[{symbol}] ctx build failed at {at.isoformat()}: {exc.__class__.__name__}: {exc}", flush=True)
            continue
        if ctx is None:
            continue

        for strategy_id, evaluator in _STRATEGIES.items():
            try:
                signal = evaluator(ctx)
            except Exception as exc:
                print(f"[{symbol}] {strategy_id} eval failed at {at.isoformat()}: {exc.__class__.__name__}: {exc}", flush=True)
                continue
            if not signal.valid:
                continue
            future_m15 = m15[i + 1 : i + 1 + _MAX_LOOKFORWARD_BARS]
            outcome = _compute_outcome(direction=signal.direction, entry=signal.proposed_entry, stop_loss=signal.stop_loss, take_profit=signal.take_profit, future_m15=future_m15)
            trades.append(_Trade(
                strategy_id=strategy_id, symbol=symbol, direction=signal.direction, entry_time=at.isoformat(),
                entry=signal.proposed_entry, stop_loss=signal.stop_loss, take_profit=signal.take_profit,
                outcome_r=outcome.get("outcome_r"), tp_hit=outcome.get("tp_hit"), sl_hit=outcome.get("sl_hit"),
                immediate_failure=outcome.get("immediate_failure"), resolution_status=outcome["resolution_status"],
                mfe_r=outcome.get("mfe_r"), mae_r=outcome.get("mae_r"), holding_bars=outcome.get("holding_bars"),
            ))

        if progress_every and instants_done % progress_every == 0:
            elapsed = time.perf_counter() - t_loop
            print(f"[{symbol}] {instants_done} instants, {len(trades)} trades so far, {elapsed:.1f}s ({elapsed/instants_done*1000:.1f}ms/instant)", flush=True)

    elapsed = time.perf_counter() - t_loop
    print(f"[{symbol}] DONE: {instants_done} instants, {len(trades)} trades, {elapsed:.1f}s ({elapsed/max(instants_done,1)*1000:.1f}ms/instant)", flush=True)
    return trades


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--symbols", nargs="+", default=list(_ALL_SYMBOLS))
    parser.add_argument("--max-instants", type=int, default=None, help="cap instants walked PER symbol (for pilot runs)")
    parser.add_argument("--progress-every", type=int, default=2000)
    parser.add_argument("--lookback-years", type=float, default=None, help="restrict the walk to the most recent N years of each symbol's history (omit for full available history)")
    parser.add_argument("--out", type=str, required=True)
    args = parser.parse_args()

    print(f"Phase 1 flags ON: {[k for k in os.environ if k.startswith('MT5_BREAKOUT_') or k.startswith('MT5_TREND_PULLBACK_') or k.startswith('MT5_SMC_CONTINUATION_')]}", flush=True)
    all_trades: list[_Trade] = []
    t0 = time.perf_counter()
    for symbol in args.symbols:
        trades = replay_symbol(symbol, max_instants=args.max_instants, progress_every=args.progress_every, lookback_years=args.lookback_years)
        all_trades.extend(trades)
        with open(args.out, "w") as f:
            json.dump([asdict(t) for t in all_trades], f)
        print(f"checkpoint written: {len(all_trades)} total trades so far -> {args.out}", flush=True)
    print(f"ALL DONE: {len(all_trades)} trades across {len(args.symbols)} symbols in {time.perf_counter()-t0:.1f}s", flush=True)


if __name__ == "__main__":
    main()
