from __future__ import annotations

from datetime import datetime
from typing import Protocol

from backend.brokers.capabilities import BrokerCapabilities
from backend.brokers.health import BrokerHealth
from backend.brokers.models import (
    BrokerAccount,
    BrokerAccountSnapshot,
    BrokerBar,
    BrokerCancelCommand,
    BrokerCancelReceipt,
    BrokerContract,
    BrokerExecution,
    BrokerOrder,
    BrokerOrderCommand,
    BrokerOrderReceipt,
    BrokerPosition,
    BrokerQuote,
    BrokerReconciliationResult,
)


class BrokerReadAdapter(Protocol):
    name: str
    capabilities: BrokerCapabilities

    async def health(self) -> BrokerHealth: ...
    async def connect(self) -> BrokerHealth: ...
    async def disconnect(self) -> BrokerHealth: ...
    async def reconnect(self) -> BrokerHealth: ...
    async def accounts(self) -> list[BrokerAccount]: ...
    async def account_snapshot(self, account_id: str) -> BrokerAccountSnapshot: ...
    async def positions(self, account_id: str) -> list[BrokerPosition]: ...
    async def open_orders(self, account_id: str) -> list[BrokerOrder]: ...
    async def executions(self, account_id: str, since: datetime | None = None) -> list[BrokerExecution]: ...
    async def resolve_contract(self, instrument_id: str) -> BrokerContract: ...
    async def quote(self, instrument_id: str) -> BrokerQuote: ...
    async def historical_bars(self, instrument_id: str, *, bar_size: str, duration: str) -> list[BrokerBar]: ...
    async def reconcile(self, account_id: str) -> BrokerReconciliationResult: ...


class BrokerOrderAdapter(Protocol):
    async def submit_order(self, command: BrokerOrderCommand) -> BrokerOrderReceipt: ...
    async def cancel_order(self, command: BrokerCancelCommand) -> BrokerCancelReceipt: ...
