"""close pre-existing gap between ORM metadata and migration history

Revision ID: 0035_close_missing_orm_tables
Revises: 0034_canonical_risk_partial_stages
Create Date: 2026-08-07 12:57:34.248558

Additive only. Discovered during 2026-08-07 disaster-recovery schema verification
(comparing backend.shared.db.Base.metadata against a DB built purely by
`alembic upgrade head`): 26 tables that current ORM models expect were never created
by any migration in the 0001->0034 chain. They must have existed on the old dev
database only because something ran Base.metadata.create_all() against it at some
point pre-incident. Autogenerated via `alembic revision --autogenerate`, then
manually trimmed to keep ONLY create_table/create_index for these 26 tables --
all drop_table/drop_index/drop_constraint churn the raw autogenerate diff proposed
against unrelated pre-existing tables (schema drift, and legacy tables no longer
ORM-mapped) was deliberately removed. See survivors/schema-verification notes in
the 2026-08-07 incident report for the full missing-table list.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0035_close_missing_orm_tables'
down_revision: Union[str, Sequence[str], None] = '0034_canonical_risk_partial_stages'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment_artifacts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('experiment_id', sa.Integer(), nullable=True),
    sa.Column('artifact_type', sa.String(), nullable=True),
    sa.Column('storage_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiment_artifacts_experiment_id'), 'experiment_artifacts', ['experiment_id'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('data_hash', sa.String(), nullable=True),
    sa.Column('code_hash', sa.String(), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experiments_name'), 'experiments', ['name'], unique=False)
    op.create_table('insider_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('insider_name', sa.String(length=128), nullable=False),
    sa.Column('insider_title', sa.String(length=128), nullable=True),
    sa.Column('transaction_type', sa.String(length=32), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('filing_date', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insider_trades_date'), 'insider_trades', ['date'], unique=False)
    op.create_index(op.f('ix_insider_trades_filing_date'), 'insider_trades', ['filing_date'], unique=False)
    op.create_index(op.f('ix_insider_trades_id'), 'insider_trades', ['id'], unique=False)
    op.create_index(op.f('ix_insider_trades_symbol'), 'insider_trades', ['symbol'], unique=False)
    op.create_table('instrument_master',
    sa.Column('canonical_id', sa.String(), nullable=False),
    sa.Column('display_symbol', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('tick_size', sa.String(), nullable=True),
    sa.Column('lot_size', sa.String(), nullable=True),
    sa.Column('vendor_mappings_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('canonical_id')
    )
    op.create_index(op.f('ix_instrument_master_display_symbol'), 'instrument_master', ['display_symbol'], unique=False)
    op.create_table('nse_fno_bhavcopy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_date', sa.String(length=16), nullable=False),
    sa.Column('instrument', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('expiry_date', sa.String(length=16), nullable=False),
    sa.Column('strike_price', sa.Float(), nullable=False),
    sa.Column('option_type', sa.String(length=8), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=False),
    sa.Column('high_price', sa.Float(), nullable=False),
    sa.Column('low_price', sa.Float(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('settle_price', sa.Float(), nullable=False),
    sa.Column('contracts', sa.Integer(), nullable=False),
    sa.Column('value_lakh', sa.Float(), nullable=False),
    sa.Column('open_interest', sa.Integer(), nullable=False),
    sa.Column('change_in_oi', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'symbol', 'expiry_date', 'option_type', 'strike_price', name='uq_nse_fno_bhavcopy_key')
    )
    op.create_index(op.f('ix_nse_fno_bhavcopy_expiry_date'), 'nse_fno_bhavcopy', ['expiry_date'], unique=False)
    op.create_index(op.f('ix_nse_fno_bhavcopy_id'), 'nse_fno_bhavcopy', ['id'], unique=False)
    op.create_index(op.f('ix_nse_fno_bhavcopy_instrument'), 'nse_fno_bhavcopy', ['instrument'], unique=False)
    op.create_index(op.f('ix_nse_fno_bhavcopy_symbol'), 'nse_fno_bhavcopy', ['symbol'], unique=False)
    op.create_index(op.f('ix_nse_fno_bhavcopy_trade_date'), 'nse_fno_bhavcopy', ['trade_date'], unique=False)
    op.create_table('portfolio_backtest_jobs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('request_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_backtest_jobs_id'), 'portfolio_backtest_jobs', ['id'], unique=False)
    op.create_table('saved_formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_formulas_created_at'), 'saved_formulas', ['created_at'], unique=False)
    op.create_index(op.f('ix_saved_formulas_id'), 'saved_formulas', ['id'], unique=False)
    op.create_index(op.f('ix_saved_formulas_name'), 'saved_formulas', ['name'], unique=False)
    op.create_table('tax_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('remaining_quantity', sa.Float(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('buy_date', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_lots_buy_date'), 'tax_lots', ['buy_date'], unique=False)
    op.create_index(op.f('ix_tax_lots_id'), 'tax_lots', ['id'], unique=False)
    op.create_index(op.f('ix_tax_lots_ticker'), 'tax_lots', ['ticker'], unique=False)
    op.create_table('user_layouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_key', sa.String(length=64), nullable=False),
    sa.Column('layouts_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_key', name='uq_user_layouts_user_key')
    )
    op.create_index(op.f('ix_user_layouts_updated_at'), 'user_layouts', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_layouts_user_key'), 'user_layouts', ['user_key'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('condition_type', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('logic', sa.String(length=5), nullable=False),
    sa.Column('delivery_channels', sa.JSON(), nullable=False),
    sa.Column('delivery_config', sa.JSON(), nullable=False),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('max_triggers', sa.Integer(), nullable=False),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('last_triggered_value', sa.Float(), nullable=True),
    sa.Column('last_notification_error', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_condition_type'), 'alerts', ['condition_type'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_symbol'), 'alerts', ['symbol'], unique=False)
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_table('chart_drawings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('tool_type', sa.String(length=32), nullable=False),
    sa.Column('coordinates', sa.JSON(), nullable=False),
    sa.Column('style', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_drawings_symbol'), 'chart_drawings', ['symbol'], unique=False)
    op.create_index(op.f('ix_chart_drawings_tool_type'), 'chart_drawings', ['tool_type'], unique=False)
    op.create_index(op.f('ix_chart_drawings_user_id'), 'chart_drawings', ['user_id'], unique=False)
    op.create_table('chart_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('layout_config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_templates_name'), 'chart_templates', ['name'], unique=False)
    op.create_index(op.f('ix_chart_templates_user_id'), 'chart_templates', ['user_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('benchmark_symbol', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('starting_cash', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_benchmark_symbol'), 'portfolios', ['benchmark_symbol'], unique=False)
    op.create_index(op.f('ix_portfolios_created_at'), 'portfolios', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=False)
    op.create_index(op.f('ix_portfolios_user_id'), 'portfolios', ['user_id'], unique=False)
    op.create_table('scan_presets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('universe', sa.String(length=64), nullable=False),
    sa.Column('timeframe', sa.String(length=16), nullable=False),
    sa.Column('liquidity_gate_json', sa.JSON(), nullable=False),
    sa.Column('rules_json', sa.JSON(), nullable=False),
    sa.Column('ranking_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_presets_created_at'), 'scan_presets', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_presets_name'), 'scan_presets', ['name'], unique=False)
    op.create_index(op.f('ix_scan_presets_universe'), 'scan_presets', ['universe'], unique=False)
    op.create_index(op.f('ix_scan_presets_updated_at'), 'scan_presets', ['updated_at'], unique=False)
    op.create_index(op.f('ix_scan_presets_user_id'), 'scan_presets', ['user_id'], unique=False)
    op.create_table('user_screens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('columns_config', sa.JSON(), nullable=False),
    sa.Column('viz_config', sa.JSON(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('upvotes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_screens_created_at'), 'user_screens', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_screens_is_public'), 'user_screens', ['is_public'], unique=False)
    op.create_index(op.f('ix_user_screens_name'), 'user_screens', ['name'], unique=False)
    op.create_index(op.f('ix_user_screens_updated_at'), 'user_screens', ['updated_at'], unique=False)
    op.create_index(op.f('ix_user_screens_user_id'), 'user_screens', ['user_id'], unique=False)
    op.create_table('virtual_portfolios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('initial_capital', sa.Float(), nullable=False),
    sa.Column('current_cash', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_portfolios_is_active'), 'virtual_portfolios', ['is_active'], unique=False)
    op.create_index(op.f('ix_virtual_portfolios_user_id'), 'virtual_portfolios', ['user_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('symbols_json', sa.JSON(), nullable=False),
    sa.Column('column_config_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_name'), 'watchlists', ['name'], unique=False)
    op.create_index(op.f('ix_watchlists_user_id'), 'watchlists', ['user_id'], unique=False)
    op.create_table('alert_triggers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('alert_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('condition_type', sa.String(length=32), nullable=False),
    sa.Column('triggered_value', sa.Float(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_triggers_alert_id'), 'alert_triggers', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_triggers_condition_type'), 'alert_triggers', ['condition_type'], unique=False)
    op.create_index(op.f('ix_alert_triggers_is_read'), 'alert_triggers', ['is_read'], unique=False)
    op.create_index(op.f('ix_alert_triggers_symbol'), 'alert_triggers', ['symbol'], unique=False)
    op.create_index(op.f('ix_alert_triggers_triggered_at'), 'alert_triggers', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_alert_triggers_user_id'), 'alert_triggers', ['user_id'], unique=False)
    op.create_table('portfolio_holdings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('cost_basis_per_share', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('lot_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', 'lot_id', name='uq_portfolio_holding_portfolio_symbol_lot')
    )
    op.create_index(op.f('ix_portfolio_holdings_created_at'), 'portfolio_holdings', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_portfolio_id'), 'portfolio_holdings', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_holdings_symbol'), 'portfolio_holdings', ['symbol'], unique=False)
    op.create_table('portfolio_transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('shares', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date', sa.String(length=16), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('lot_id', sa.String(length=64), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_transactions_created_at'), 'portfolio_transactions', ['created_at'], unique=False)
    op.create_index(op.f('ix_portfolio_transactions_date'), 'portfolio_transactions', ['date'], unique=False)
    op.create_index(op.f('ix_portfolio_transactions_portfolio_id'), 'portfolio_transactions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_portfolio_transactions_symbol'), 'portfolio_transactions', ['symbol'], unique=False)
    op.create_index(op.f('ix_portfolio_transactions_type'), 'portfolio_transactions', ['type'], unique=False)
    op.create_table('scan_alert_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('preset_id', sa.String(length=36), nullable=True),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('setup_type', sa.String(length=64), nullable=False),
    sa.Column('trigger_level', sa.Float(), nullable=False),
    sa.Column('invalidation_level', sa.Float(), nullable=True),
    sa.Column('near_trigger_pct', sa.Float(), nullable=False),
    sa.Column('dedupe_minutes', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_event_type', sa.String(length=32), nullable=True),
    sa.Column('last_event_at', sa.DateTime(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['scan_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_alert_rules_created_at'), 'scan_alert_rules', ['created_at'], unique=False)
    op.create_index(op.f('ix_scan_alert_rules_enabled'), 'scan_alert_rules', ['enabled'], unique=False)
    op.create_index(op.f('ix_scan_alert_rules_preset_id'), 'scan_alert_rules', ['preset_id'], unique=False)
    op.create_index(op.f('ix_scan_alert_rules_setup_type'), 'scan_alert_rules', ['setup_type'], unique=False)
    op.create_index(op.f('ix_scan_alert_rules_symbol'), 'scan_alert_rules', ['symbol'], unique=False)
    op.create_index(op.f('ix_scan_alert_rules_updated_at'), 'scan_alert_rules', ['updated_at'], unique=False)
    op.create_index(op.f('ix_scan_alert_rules_user_id'), 'scan_alert_rules', ['user_id'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('preset_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('meta_json', sa.JSON(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['preset_id'], ['scan_presets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_runs_finished_at'), 'scan_runs', ['finished_at'], unique=False)
    op.create_index(op.f('ix_scan_runs_preset_id'), 'scan_runs', ['preset_id'], unique=False)
    op.create_index(op.f('ix_scan_runs_started_at'), 'scan_runs', ['started_at'], unique=False)
    op.create_index(op.f('ix_scan_runs_status'), 'scan_runs', ['status'], unique=False)
    op.create_index(op.f('ix_scan_runs_user_id'), 'scan_runs', ['user_id'], unique=False)
    op.create_table('virtual_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('order_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('sl_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('fill_time', sa.DateTime(), nullable=True),
    sa.Column('slippage_bps', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('signal_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['virtual_portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_orders_order_type'), 'virtual_orders', ['order_type'], unique=False)
    op.create_index(op.f('ix_virtual_orders_portfolio_id'), 'virtual_orders', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_virtual_orders_side'), 'virtual_orders', ['side'], unique=False)
    op.create_index(op.f('ix_virtual_orders_status'), 'virtual_orders', ['status'], unique=False)
    op.create_index(op.f('ix_virtual_orders_symbol'), 'virtual_orders', ['symbol'], unique=False)
    op.create_table('virtual_positions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_entry_price', sa.Float(), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['virtual_portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_virtual_position_portfolio_symbol')
    )
    op.create_index(op.f('ix_virtual_positions_portfolio_id'), 'virtual_positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_virtual_positions_symbol'), 'virtual_positions', ['symbol'], unique=False)
    op.create_table('scan_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('setup_type', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('signal_ts', sa.DateTime(), nullable=True),
    sa.Column('levels_json', sa.JSON(), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.Column('explain_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['scan_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'symbol', 'setup_type', name='uq_scan_result_run_symbol_setup')
    )
    op.create_index(op.f('ix_scan_results_run_id'), 'scan_results', ['run_id'], unique=False)
    op.create_index(op.f('ix_scan_results_score'), 'scan_results', ['score'], unique=False)
    op.create_index(op.f('ix_scan_results_setup_type'), 'scan_results', ['setup_type'], unique=False)
    op.create_index(op.f('ix_scan_results_symbol'), 'scan_results', ['symbol'], unique=False)
    op.create_table('virtual_trades',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('pnl_realized', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['virtual_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['portfolio_id'], ['virtual_portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_virtual_trades_order_id'), 'virtual_trades', ['order_id'], unique=False)
    op.create_index(op.f('ix_virtual_trades_portfolio_id'), 'virtual_trades', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_virtual_trades_side'), 'virtual_trades', ['side'], unique=False)
    op.create_index(op.f('ix_virtual_trades_symbol'), 'virtual_trades', ['symbol'], unique=False)
    op.create_index(op.f('ix_virtual_trades_timestamp'), 'virtual_trades', ['timestamp'], unique=False)
    # ### end Alembic commands ###
    # NOTE: manually trimmed from the raw autogenerate output. This migration closes a pre-existing
    # gap where these 26 ORM-mapped tables were never captured by any migration (they must have been
    # created ad hoc via create_all() on the pre-incident dev DB). Only additive create_table/create_index
    # operations for those 26 tables are kept. All drop_table/drop_index/drop_constraint/create_index
    # churn the autogenerate diff proposed against UNRELATED pre-existing tables (schema drift from
    # historical migrations, and 19 legacy tables no longer ORM-mapped) has been deliberately removed —
    # this migration must only add what's missing, never touch anything else.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_virtual_trades_timestamp'), table_name='virtual_trades')
    op.drop_index(op.f('ix_virtual_trades_symbol'), table_name='virtual_trades')
    op.drop_index(op.f('ix_virtual_trades_side'), table_name='virtual_trades')
    op.drop_index(op.f('ix_virtual_trades_portfolio_id'), table_name='virtual_trades')
    op.drop_index(op.f('ix_virtual_trades_order_id'), table_name='virtual_trades')
    op.drop_table('virtual_trades')
    op.drop_index(op.f('ix_scan_results_symbol'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_setup_type'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_score'), table_name='scan_results')
    op.drop_index(op.f('ix_scan_results_run_id'), table_name='scan_results')
    op.drop_table('scan_results')
    op.drop_index(op.f('ix_virtual_positions_symbol'), table_name='virtual_positions')
    op.drop_index(op.f('ix_virtual_positions_portfolio_id'), table_name='virtual_positions')
    op.drop_table('virtual_positions')
    op.drop_index(op.f('ix_virtual_orders_symbol'), table_name='virtual_orders')
    op.drop_index(op.f('ix_virtual_orders_status'), table_name='virtual_orders')
    op.drop_index(op.f('ix_virtual_orders_side'), table_name='virtual_orders')
    op.drop_index(op.f('ix_virtual_orders_portfolio_id'), table_name='virtual_orders')
    op.drop_index(op.f('ix_virtual_orders_order_type'), table_name='virtual_orders')
    op.drop_table('virtual_orders')
    op.drop_index(op.f('ix_scan_runs_user_id'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_status'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_started_at'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_preset_id'), table_name='scan_runs')
    op.drop_index(op.f('ix_scan_runs_finished_at'), table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index(op.f('ix_scan_alert_rules_user_id'), table_name='scan_alert_rules')
    op.drop_index(op.f('ix_scan_alert_rules_updated_at'), table_name='scan_alert_rules')
    op.drop_index(op.f('ix_scan_alert_rules_symbol'), table_name='scan_alert_rules')
    op.drop_index(op.f('ix_scan_alert_rules_setup_type'), table_name='scan_alert_rules')
    op.drop_index(op.f('ix_scan_alert_rules_preset_id'), table_name='scan_alert_rules')
    op.drop_index(op.f('ix_scan_alert_rules_enabled'), table_name='scan_alert_rules')
    op.drop_index(op.f('ix_scan_alert_rules_created_at'), table_name='scan_alert_rules')
    op.drop_table('scan_alert_rules')
    op.drop_index(op.f('ix_portfolio_transactions_type'), table_name='portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_transactions_symbol'), table_name='portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_transactions_portfolio_id'), table_name='portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_transactions_date'), table_name='portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_transactions_created_at'), table_name='portfolio_transactions')
    op.drop_table('portfolio_transactions')
    op.drop_index(op.f('ix_portfolio_holdings_symbol'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_portfolio_id'), table_name='portfolio_holdings')
    op.drop_index(op.f('ix_portfolio_holdings_created_at'), table_name='portfolio_holdings')
    op.drop_table('portfolio_holdings')
    op.drop_index(op.f('ix_alert_triggers_user_id'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_triggered_at'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_symbol'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_is_read'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_condition_type'), table_name='alert_triggers')
    op.drop_index(op.f('ix_alert_triggers_alert_id'), table_name='alert_triggers')
    op.drop_table('alert_triggers')
    op.drop_index(op.f('ix_watchlists_user_id'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_name'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_virtual_portfolios_user_id'), table_name='virtual_portfolios')
    op.drop_index(op.f('ix_virtual_portfolios_is_active'), table_name='virtual_portfolios')
    op.drop_table('virtual_portfolios')
    op.drop_index(op.f('ix_user_screens_user_id'), table_name='user_screens')
    op.drop_index(op.f('ix_user_screens_updated_at'), table_name='user_screens')
    op.drop_index(op.f('ix_user_screens_name'), table_name='user_screens')
    op.drop_index(op.f('ix_user_screens_is_public'), table_name='user_screens')
    op.drop_index(op.f('ix_user_screens_created_at'), table_name='user_screens')
    op.drop_table('user_screens')
    op.drop_index(op.f('ix_scan_presets_user_id'), table_name='scan_presets')
    op.drop_index(op.f('ix_scan_presets_updated_at'), table_name='scan_presets')
    op.drop_index(op.f('ix_scan_presets_universe'), table_name='scan_presets')
    op.drop_index(op.f('ix_scan_presets_name'), table_name='scan_presets')
    op.drop_index(op.f('ix_scan_presets_created_at'), table_name='scan_presets')
    op.drop_table('scan_presets')
    op.drop_index(op.f('ix_portfolios_user_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_created_at'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_benchmark_symbol'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_chart_templates_user_id'), table_name='chart_templates')
    op.drop_index(op.f('ix_chart_templates_name'), table_name='chart_templates')
    op.drop_table('chart_templates')
    op.drop_index(op.f('ix_chart_drawings_user_id'), table_name='chart_drawings')
    op.drop_index(op.f('ix_chart_drawings_tool_type'), table_name='chart_drawings')
    op.drop_index(op.f('ix_chart_drawings_symbol'), table_name='chart_drawings')
    op.drop_table('chart_drawings')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_symbol'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_condition_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_user_layouts_user_key'), table_name='user_layouts')
    op.drop_index(op.f('ix_user_layouts_updated_at'), table_name='user_layouts')
    op.drop_table('user_layouts')
    op.drop_index(op.f('ix_tax_lots_ticker'), table_name='tax_lots')
    op.drop_index(op.f('ix_tax_lots_id'), table_name='tax_lots')
    op.drop_index(op.f('ix_tax_lots_buy_date'), table_name='tax_lots')
    op.drop_table('tax_lots')
    op.drop_index(op.f('ix_saved_formulas_name'), table_name='saved_formulas')
    op.drop_index(op.f('ix_saved_formulas_id'), table_name='saved_formulas')
    op.drop_index(op.f('ix_saved_formulas_created_at'), table_name='saved_formulas')
    op.drop_table('saved_formulas')
    op.drop_index(op.f('ix_portfolio_backtest_jobs_id'), table_name='portfolio_backtest_jobs')
    op.drop_table('portfolio_backtest_jobs')
    op.drop_index(op.f('ix_nse_fno_bhavcopy_trade_date'), table_name='nse_fno_bhavcopy')
    op.drop_index(op.f('ix_nse_fno_bhavcopy_symbol'), table_name='nse_fno_bhavcopy')
    op.drop_index(op.f('ix_nse_fno_bhavcopy_instrument'), table_name='nse_fno_bhavcopy')
    op.drop_index(op.f('ix_nse_fno_bhavcopy_id'), table_name='nse_fno_bhavcopy')
    op.drop_index(op.f('ix_nse_fno_bhavcopy_expiry_date'), table_name='nse_fno_bhavcopy')
    op.drop_table('nse_fno_bhavcopy')
    op.drop_index(op.f('ix_instrument_master_display_symbol'), table_name='instrument_master')
    op.drop_table('instrument_master')
    op.drop_index(op.f('ix_insider_trades_symbol'), table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_id'), table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_filing_date'), table_name='insider_trades')
    op.drop_index(op.f('ix_insider_trades_date'), table_name='insider_trades')
    op.drop_table('insider_trades')
    op.drop_index(op.f('ix_experiments_name'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_experiment_artifacts_experiment_id'), table_name='experiment_artifacts')
    op.drop_table('experiment_artifacts')
    # ### end Alembic commands ###
