from __future__ import annotations

from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Float, Index, Integer, JSON, String, Text, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from backend.shared.db import Base


def utcnow() -> datetime:
    return datetime.now(timezone.utc)


class HistoricalIngestionRunORM(Base):
    """One row per backfill/incremental-ingestion invocation (Part 3/22/24). Never edited after
    completion -- the durable record of what was actually fetched, from where, and how much of
    it was trustworthy, independent of what ended up persisted in mt5_canonical_candles."""

    __tablename__ = "historical_ingestion_runs"

    run_id: Mapped[str] = mapped_column(String(96), primary_key=True)
    provider: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    canonical_symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    broker_symbol: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    timeframe: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    requested_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    requested_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    bars_fetched: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    bars_persisted: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    bars_skipped_existing: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    bars_flagged_suspect: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    bars_flagged_invalid: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    # [{"gap_start": iso, "gap_end": iso, "bars_missing_estimate": int}, ...] -- detected BEFORE
    # fetching (existing coverage vs requested range), not a post-hoc guess.
    gaps_detected: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    # RUNNING | COMPLETED | FAILED | PARTIAL (fetched something but hit an error before covering
    # the full requested range -- distinct from COMPLETED so a caller knows to retry the tail).
    status: Mapped[str] = mapped_column(String(24), nullable=False, default="RUNNING", index=True)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    duration_ms: Mapped[float | None] = mapped_column(Float, nullable=True)


class HistoricalProviderReconciliationORM(Base):
    """Persisted result of quality.compare_provider_overlap() (Part 4) -- one row per
    symbol/timeframe/provider-pair comparison run, so provider-disagreement status is queryable
    (Part 22) rather than only visible in an ephemeral API response."""

    __tablename__ = "historical_provider_reconciliations"

    reconciliation_id: Mapped[str] = mapped_column(String(96), primary_key=True)
    canonical_symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    timeframe: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    left_provider: Mapped[str] = mapped_column(String(32), nullable=False)
    right_provider: Mapped[str] = mapped_column(String(32), nullable=False)
    overlapping_bars: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    median_relative_diff: Mapped[float | None] = mapped_column(Float, nullable=True)
    mean_relative_diff: Mapped[float | None] = mapped_column(Float, nullable=True)
    max_relative_diff: Mapped[float | None] = mapped_column(Float, nullable=True)
    # NO_OVERLAP | NO_COMPARABLE_PRICES | CONSISTENT | DIVERGENT | INCOMPATIBLE
    status: Mapped[str] = mapped_column(String(24), nullable=False, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)


class HistoricalReplayRunORM(Base):
    """One row per point-in-time strategy-replay batch (Part 6/24). `strategy_version` is the
    cache-busting/isolation key (Part 11's "changing strategy logic must not consume statistics
    generated by an older implementation") -- see historical_intelligence/replay.py::
    STRATEGY_REPLAY_VERSION."""

    __tablename__ = "historical_replay_runs"

    run_id: Mapped[str] = mapped_column(String(96), primary_key=True)
    strategy_version: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    canonical_symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    timeframe: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    requested_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    requested_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    bars_replayed: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    candidates_generated: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    status: Mapped[str] = mapped_column(String(24), nullable=False, default="RUNNING", index=True)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    started_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)
    completed_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    duration_ms: Mapped[float | None] = mapped_column(Float, nullable=True)


class HistoricalReplayParityCheckORM(Base):
    """One row per parity check between the replay engine's output and a REAL, already-recorded
    live MT5CandidateEvaluationORM row (Part 6's "verify point-in-time replay parity before
    building intelligence on top of it"). This table is the durable evidence backing that claim
    -- never edited after creation."""

    __tablename__ = "historical_replay_parity_checks"

    check_id: Mapped[str] = mapped_column(String(96), primary_key=True)
    live_evaluation_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    canonical_symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    strategy_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    live_direction: Mapped[str | None] = mapped_column(String(16), nullable=True)
    replay_direction: Mapped[str | None] = mapped_column(String(16), nullable=True)
    live_entry: Mapped[float | None] = mapped_column(Float, nullable=True)
    replay_entry: Mapped[float | None] = mapped_column(Float, nullable=True)
    live_stop_loss: Mapped[float | None] = mapped_column(Float, nullable=True)
    replay_stop_loss: Mapped[float | None] = mapped_column(Float, nullable=True)
    live_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    replay_confidence: Mapped[float | None] = mapped_column(Float, nullable=True)
    # MATCH | PARTIAL_MATCH | MISMATCH | REPLAY_MISSING | LIVE_DATA_INSUFFICIENT
    verdict: Mapped[str] = mapped_column(String(24), nullable=False, index=True)
    diff_detail: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)


class MT5CandleRevisionORM(Base):
    """Immutable, append-only revision history for a canonical bar (Option A -- confirmed
    necessary: mt5_canonical_candles rows are upserted via db.merge() on every re-fetch, so a
    later fetch silently overwrites whatever OHLC the live engine actually decided against,
    with no way to recover the original value afterward -- proven directly against this
    deployment's own data on 2026-08-12: a single 30-day historical backfill stamped the same
    `updated_at` across ~364,000 already-live-captured rows).

    One row per MATERIALLY DIFFERENT observed OHLC for a given (provider, broker_symbol,
    timeframe, bar_timestamp) -- never updated after insert. `bar_timestamp` is the value
    exactly as reported by the provider (broker-server time for MT5, NEVER silently rewritten);
    `bar_timestamp_utc` is that same instant corrected using `broker_utc_offset_minutes` as
    detected at capture time -- every point-in-time comparison in replay.py uses ONLY this
    column, never the raw provider-labeled one. `finalized=True` marks a bar considered stable
    enough (per quality.is_finalized's age policy) that a differing re-fetch is no longer
    trusted to overwrite it -- see ingestion.py's write path for the enforcement."""

    __tablename__ = "mt5_candle_revisions"

    revision_id: Mapped[str] = mapped_column(String(160), primary_key=True)
    provider: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    canonical_symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    broker_symbol: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    timeframe: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    bar_timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    bar_timestamp_utc: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    broker_utc_offset_minutes: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    observed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    revision_number: Mapped[int] = mapped_column(Integer, nullable=False, default=1)
    open: Mapped[float] = mapped_column(Float, nullable=False)
    high: Mapped[float] = mapped_column(Float, nullable=False)
    low: Mapped[float] = mapped_column(Float, nullable=False)
    close: Mapped[float] = mapped_column(Float, nullable=False)
    tick_volume: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    spread: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    real_volume: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    finalized: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, index=True)
    # Set only on a revision observed AFTER the bar was already finalized (a value that differed
    # from the trusted finalized value, and was therefore NOT applied to mt5_canonical_candles)
    # -- an anomaly worth surfacing, never silently dropped.
    post_finalization_anomaly: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False, index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)

    __table_args__ = (
        UniqueConstraint("provider", "broker_symbol", "timeframe", "bar_timestamp", "revision_number", name="uq_mt5_candle_revision"),
        Index("ix_mt5_candle_revision_lookup", "provider", "broker_symbol", "timeframe", "bar_timestamp", "observed_at"),
    )


class MT5DecisionSnapshotORM(Base):
    """Option B: the EXACT candle slices and derived context the live engine used to generate
    ONE candidate, captured at generation time -- the authoritative parity-verification source.
    When present, replay.py never needs to reconstruct "what bars were used" via timestamp
    comparison (and therefore can never be tripped up by the broker-server-time-vs-UTC labeling
    issue, or by a later bar revision) -- it reads back exactly what live saw. Captured
    best-effort from backend/brokers/mt5/autonomous.py's own in-memory per-cycle context cache,
    strictly AFTER the live decision is already made (see historical_intelligence/
    snapshot_capture.py) -- never read by the live trading engine itself, and a capture failure
    can never affect a live decision."""

    __tablename__ = "mt5_decision_snapshots"

    snapshot_id: Mapped[str] = mapped_column(String(160), primary_key=True)
    evaluation_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    cycle_id: Mapped[str] = mapped_column(String(96), nullable=False, index=True)
    account_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    canonical_symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    broker_symbol: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    decision_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)
    m15_rows: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    h1_rows: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    h4_rows: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    bid: Mapped[float | None] = mapped_column(Float, nullable=True)
    ask: Mapped[float | None] = mapped_column(Float, nullable=True)
    spread: Mapped[float | None] = mapped_column(Float, nullable=True)
    regime: Mapped[str | None] = mapped_column(String(64), nullable=True)
    smc_evidence: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    symbol_info: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)

    __table_args__ = (UniqueConstraint("evaluation_id", name="uq_mt5_decision_snapshot_evaluation"),)


# Bumped whenever the fingerprint FIELD SET or bucketing logic changes in a way that could put
# two setups that used to hash identically into different peer groups (or vice versa) --
# consumers must never silently mix statistics computed under different versions. NOT bumped for
# unrelated code changes. See fingerprint.py::FINGERPRINT_VERSION (kept in sync with this).
FINGERPRINT_VERSION = "fp-v2"  # bumped: peer_group_hash now uses a coarser hard-match set
# (symbol/direction/strategy/strategy_version/regime_broad/atr_regime/stop_distance_atr_bucket)
# -- see fingerprint.py's module docstring. fp-v1 rows remain valid under their own version;
# statistics.py scopes by fingerprint_version so the two never silently mix.
HISTORICAL_INTELLIGENCE_VERSION = "hi-v1"


class HistoricalPatternFingerprintORM(Base):
    """One row per replayed historical setup (Part 1/2). Deliberately NOT one row per raw
    candle/price -- this is the peer-groupable, versioned "what kind of setup was this"
    record, built from the SAME production feature context (StrategyContext/summarize_smc_
    evidence) every live candidate already gets, so live and historical setups are directly
    comparable. `peer_group_hash` is deliberately computed from a SUBSET of coarse, bucketed
    fields (never raw prices) -- see fingerprint.py's module docstring for exactly which ones
    and why -- so meaningfully-similar setups group together instead of every setup being
    unique. The full field set below is still stored (not just the hash) so future querying
    isn't limited to whatever went into today's peer-group definition.

    Versioning (Part 2): historical_intelligence_version/strategy_version/fingerprint_version
    are stamped on every row. `strategy_version` is replay.STRATEGY_REPLAY_VERSION -- if that
    ever bumps (production strategy logic changed), pattern statistics MUST NOT silently mix
    fingerprints from before and after; callers filter on strategy_version, never assume it's
    constant. `source_quality_tier` (SNAPSHOT | RECONSTRUCTED) and `provider`/`proxy` carry the
    evidentiary trustworthiness of the underlying bars forward into every statistic built on
    top (Part 22 -- "never consume ... without explicit quality status")."""

    __tablename__ = "historical_pattern_fingerprints"

    fingerprint_id: Mapped[str] = mapped_column(String(160), primary_key=True)
    source_evaluation_id: Mapped[str | None] = mapped_column(String(128), nullable=True, index=True)
    replay_run_id: Mapped[str | None] = mapped_column(String(96), nullable=True, index=True)

    historical_intelligence_version: Mapped[str] = mapped_column(String(32), nullable=False, index=True, default=HISTORICAL_INTELLIGENCE_VERSION)
    strategy_version: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    fingerprint_version: Mapped[str] = mapped_column(String(32), nullable=False, index=True, default=FINGERPRINT_VERSION)
    # SNAPSHOT | RECONSTRUCTED -- see replay.py's source hierarchy docstring.
    source_quality_tier: Mapped[str] = mapped_column(String(24), nullable=False, index=True)
    provider: Mapped[str] = mapped_column(String(32), nullable=False, index=True, default="MT5")
    proxy: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)

    canonical_symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    direction: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    anchor_strategy: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    contributing_strategies: Mapped[list] = mapped_column(JSON, nullable=False, default=list)
    strategy_family: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)

    regime: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    # Coarse HARD-MATCH bucket derived from `regime` (TRENDING/BREAKOUT/REVERSAL/RANGING/
    # UNKNOWN) -- part of peer_group_hash as of fp-v2; `regime` itself keeps full granularity
    # and is used by similarity.py's weighting, never by the hash.
    regime_broad: Mapped[str | None] = mapped_column(String(16), nullable=True, index=True)
    session: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    confidence_band: Mapped[str | None] = mapped_column(String(32), nullable=True)

    m15_trend: Mapped[str | None] = mapped_column(String(16), nullable=True)
    h1_trend: Mapped[str | None] = mapped_column(String(16), nullable=True)
    h4_trend: Mapped[str | None] = mapped_column(String(16), nullable=True)

    bos_present: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    choch_present: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    mss_present: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    displacement_present: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    liquidity_sweep_present: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    liquidity_location: Mapped[str] = mapped_column(String(16), nullable=False, default="none")  # buy_side | sell_side | none
    fvg_state: Mapped[str] = mapped_column(String(16), nullable=False, default="none")  # bullish | bearish | mixed | none
    order_block_state: Mapped[str] = mapped_column(String(16), nullable=False, default="none")
    premium_discount_position: Mapped[str | None] = mapped_column(String(32), nullable=True)
    support_resistance_context: Mapped[str | None] = mapped_column(String(32), nullable=True)

    atr_regime: Mapped[str | None] = mapped_column(String(16), nullable=True, index=True)  # LOW|NORMAL|HIGH|EXTREME
    atr_percentile: Mapped[float | None] = mapped_column(Float, nullable=True)
    volatility_regime: Mapped[str | None] = mapped_column(String(16), nullable=True)
    spread_regime: Mapped[str] = mapped_column(String(16), nullable=False, default="unknown")  # TIGHT|NORMAL|WIDE|unknown
    stop_distance_atr_bucket: Mapped[str | None] = mapped_column(String(16), nullable=True)
    planned_rr_bucket: Mapped[str | None] = mapped_column(String(16), nullable=True)

    day_of_week: Mapped[int | None] = mapped_column(Integer, nullable=True)  # 0=Monday .. 6=Sunday
    time_of_day_bucket: Mapped[str | None] = mapped_column(String(16), nullable=True)  # ASIAN|LONDON|NY_OVERLAP|NY|OTHER
    economic_event_context: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)

    entry: Mapped[float] = mapped_column(Float, nullable=False)
    stop_loss: Mapped[float] = mapped_column(Float, nullable=False)
    take_profit: Mapped[float] = mapped_column(Float, nullable=False)
    entry_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, index=True)

    # Deterministic peer-group key -- see fingerprint.py::peer_group_hash for the exact field
    # subset. Indexed for fast "find similar setups" lookups; this is what pattern statistics
    # actually group by.
    peer_group_hash: Mapped[str] = mapped_column(String(64), nullable=False, index=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)

    __table_args__ = (
        Index("ix_hpf_peer_group_lookup", "peer_group_hash", "strategy_version", "fingerprint_version"),
        Index("ix_hpf_symbol_strategy", "canonical_symbol", "anchor_strategy"),
    )


class HistoricalSetupOutcomeORM(Base):
    """One row per fingerprint (Part 3), computed EXCLUSIVELY from candles strictly AFTER
    entry_time -- never used for signal generation, only for labeling what happened next. See
    outcomes.py's module docstring for the exact walk-forward algorithm (reused, not
    reimplemented, from backend/brokers/mt5/outcome_resolver.py's shadow-candidate resolution:
    same R formula, same SL-touched-first tie-break when a single candle's range spans both
    levels)."""

    __tablename__ = "historical_setup_outcomes"

    outcome_id: Mapped[str] = mapped_column(String(160), primary_key=True)
    fingerprint_id: Mapped[str] = mapped_column(String(160), nullable=False, unique=True, index=True)

    # PENDING: future data insufficient to resolve yet (setup too recent). RESOLVED: reached a
    # terminal state. INSUFFICIENT_FUTURE_DATA: replay range simply doesn't extend far enough
    # (e.g. near the edge of ingested history) -- distinct from PENDING (which implies the setup
    # is *live-recent*), so callers never conflate "still open" with "we ran out of history".
    resolution_status: Mapped[str] = mapped_column(String(32), nullable=False, index=True, default="PENDING")

    outcome_r: Mapped[float | None] = mapped_column(Float, nullable=True)
    net_outcome_r: Mapped[float | None] = mapped_column(Float, nullable=True)  # None when cost cannot be honestly modeled (see outcomes.py)
    mfe_r: Mapped[float | None] = mapped_column(Float, nullable=True)
    mae_r: Mapped[float | None] = mapped_column(Float, nullable=True)
    tp_hit: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    sl_hit: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    reached_0_25r: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    reached_0_5r: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    reached_0_75r: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    reached_1r: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    reached_1_5r: Mapped[bool | None] = mapped_column(Boolean, nullable=True)
    reached_2r: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    # Reached a significant adverse excursion (>= 80% of planned risk) BEFORE ever reaching
    # +0.25R -- see outcomes.py for the exact definition and rationale.
    immediate_failure: Mapped[bool | None] = mapped_column(Boolean, nullable=True)

    time_to_0_5r_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)
    time_to_1r_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)
    time_to_mfe_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)
    holding_duration_seconds: Mapped[float | None] = mapped_column(Float, nullable=True)

    bars_scanned: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    # HIGH | ACCEPTABLE | APPROXIMATE | UNTRUSTED -- the WORST tier among every future candle
    # actually used to compute this outcome (see outcomes.py's module docstring for the exact
    # source-hierarchy definition of each tier). UNTRUSTED outcomes are still persisted here for
    # audit but statistics.py's pattern_statistics excludes them from every active aggregate.
    data_quality: Mapped[str] = mapped_column(String(16), nullable=False, default="UNTRUSTED", index=True)
    resolved_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)


class StrategyReplayTrustORM(Base):
    """Per-strategy Historical Intelligence trust state (Part 6) -- DELIBERATELY separate from
    pattern-level statistical reliability (HistoricalSetupOutcomeORM aggregates answer "is this
    PATTERN's sample big enough/consistent enough"; this table answers "can we trust REPLAY
    ITSELF for this strategy at all", i.e. does reconstructed-tier replay actually reproduce
    what the strategy does live). Both gates must pass before Historical Intelligence may
    influence a live decision for a given strategy (see trust_gating.py). Never hardcoded
    permanently -- recomputed from real parity evidence (historical_replay_parity_checks) each
    time trust_gating.recompute_trust() runs; this table just persists the LATEST computed
    verdict plus its full evidence for observability, one row per strategy_id (upserted)."""

    __tablename__ = "strategy_replay_trust"

    strategy_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    # HIST_INTEL_ACTIVE | HIST_INTEL_OBSERVE_ONLY | HIST_INTEL_UNTRUSTED_REPLAY
    trust_state: Mapped[str] = mapped_column(String(32), nullable=False, index=True, default="HIST_INTEL_UNTRUSTED_REPLAY")
    reason: Mapped[str] = mapped_column(Text, nullable=False, default="")

    sample_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    exact_match_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    direction_match_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    strategy_presence_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    regime_match_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    snapshot_tier_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    snapshot_tier_sample_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    strategy_version: Mapped[str | None] = mapped_column(String(64), nullable=True)
    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)

    __table_args__ = (Index("ix_srt_trust_state", "trust_state"),)


class HistoricalIntelligenceObservationORM(Base):
    """One row per live candidate's Historical Intelligence evaluation (Part 21 observability),
    keyed by evaluation_id -- a SEPARATE table from MT5CandidateEvaluationORM (which is
    immutable-by-design; see candidate_evaluation.py) so this can be written by a later hook in
    the same cycle without violating that immutability guarantee. Captures the full entry_
    intelligence.py result, whether or not it actually influenced anything -- status/reason are
    populated even when historical intelligence was unavailable (mode off, strategy untrusted,
    pattern sample insufficient), so "why didn't this apply" is always answerable."""

    __tablename__ = "historical_intelligence_observations"

    observation_id: Mapped[str] = mapped_column(String(160), primary_key=True)
    evaluation_id: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    cycle_id: Mapped[str] = mapped_column(String(96), nullable=False, index=True)
    strategy_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)

    status: Mapped[str] = mapped_column(String(24), nullable=False, index=True)  # EVALUATED | UNAVAILABLE
    reason: Mapped[str | None] = mapped_column(String(64), nullable=True)
    trust_state: Mapped[str | None] = mapped_column(String(32), nullable=True)
    reliability: Mapped[str | None] = mapped_column(String(24), nullable=True)
    sample_size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    expectancy_r: Mapped[float | None] = mapped_column(Float, nullable=True)
    profit_factor: Mapped[float | None] = mapped_column(Float, nullable=True)
    immediate_failure_probability: Mapped[float | None] = mapped_column(Float, nullable=True)
    probability_0_5r: Mapped[float | None] = mapped_column(Float, nullable=True)
    probability_1r: Mapped[float | None] = mapped_column(Float, nullable=True)
    probability_1_5r: Mapped[float | None] = mapped_column(Float, nullable=True)
    probability_2r: Mapped[float | None] = mapped_column(Float, nullable=True)

    historical_score: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    ranking_adjustment: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    ranking_adjustment_applied: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    defer_reject_reason: Mapped[str | None] = mapped_column(String(64), nullable=True)
    peer_group_hash: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    source: Mapped[str | None] = mapped_column(String(16), nullable=True)
    # EXACT_PEER_GROUP | SIMILARITY_WEIGHTED -- which evidence source actually produced this
    # evaluation's reliability/statistics (see entry_intelligence.py::_pick_evaluation_source).
    # Never hidden inside the score -- always visible which lens was used.
    evaluation_source: Mapped[str | None] = mapped_column(String(24), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)

    __table_args__ = (UniqueConstraint("evaluation_id", name="uq_hio_evaluation"),)


class AdaptiveIntelligenceObservationORM(Base):
    """One row per Adaptive Trade Manager management-cycle decision's Historical Intelligence
    evaluation (Part 21 -- "historical state sample, continuation probability, reversal
    probability, expected additional R, recommended existing action, whether recommendation was
    applied, reason"). Written from adaptive_intelligence.py::record_observation, hooked
    alongside event_capture.capture_management_event in service.py::_monitor_cycle -- AFTER
    _select_action/_persist_action have already finalized the real decision, BEFORE
    _can_execute/_execute_action run. Strictly observational: `recommendation_applied` is
    always False in this phase (see adaptive_intelligence.py's module docstring for why live
    application is deferred)."""

    __tablename__ = "adaptive_intelligence_observations"

    observation_id: Mapped[str] = mapped_column(String(160), primary_key=True)
    position_id: Mapped[str] = mapped_column(String(96), nullable=False, index=True)
    cycle_run_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    strategy: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    symbol: Mapped[str] = mapped_column(String(32), nullable=False, index=True)

    status: Mapped[str] = mapped_column(String(24), nullable=False, index=True)  # EVALUATED | UNAVAILABLE
    reason: Mapped[str | None] = mapped_column(String(64), nullable=True)
    reliability: Mapped[str | None] = mapped_column(String(24), nullable=True)
    resolved_sample_size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)

    probability_reach_original_tp: Mapped[float | None] = mapped_column(Float, nullable=True)
    probability_reach_plus_1r: Mapped[float | None] = mapped_column(Float, nullable=True)
    probability_reversal: Mapped[float | None] = mapped_column(Float, nullable=True)
    probability_round_trip: Mapped[float | None] = mapped_column(Float, nullable=True)
    expected_additional_r: Mapped[float | None] = mapped_column(Float, nullable=True)

    actual_action_type: Mapped[str] = mapped_column(String(64), nullable=False)
    recommended_action_type: Mapped[str | None] = mapped_column(String(64), nullable=True)
    recommendation_applied: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    peer_group_hash: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)

    __table_args__ = (Index("ix_aio_position_time", "position_id", "created_at"),)


class HistoricalWalkForwardResultORM(Base):
    """Persisted result of walk_forward.run_walk_forward (Phase 1) -- one row per (filter
    combination) run, upserted by a deterministic key so re-running against a growing corpus
    naturally supersedes the previous result rather than accumulating unbounded history. This is
    an EVIDENCE record, not a live gate by itself -- entry_intelligence.py reads the latest row
    for a strategy as a third gate alongside trust_gating/statistics."""

    __tablename__ = "historical_walk_forward_results"

    result_id: Mapped[str] = mapped_column(String(160), primary_key=True)
    anchor_strategy: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)
    canonical_symbol: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    regime: Mapped[str | None] = mapped_column(String(64), nullable=True)
    session: Mapped[str | None] = mapped_column(String(32), nullable=True)
    confidence_band: Mapped[str | None] = mapped_column(String(32), nullable=True)
    peer_group_hash: Mapped[str | None] = mapped_column(String(64), nullable=True, index=True)

    edge_stability: Mapped[str] = mapped_column(String(24), nullable=False, index=True)
    total_n: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    train_n: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    oos_n: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    train_expectancy_r: Mapped[float | None] = mapped_column(Float, nullable=True)
    oos_expectancy_r: Mapped[float | None] = mapped_column(Float, nullable=True)
    degradation_pct: Mapped[float | None] = mapped_column(Float, nullable=True)
    train_stats: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)
    oos_stats: Mapped[dict] = mapped_column(JSON, nullable=False, default=dict)

    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False, default=utcnow, index=True)

    __table_args__ = (Index("ix_hwfr_strategy_computed", "anchor_strategy", "computed_at"),)
